#!/bin/bash

# Version Bump Script for Simpler Fuel
# Updates version across all configuration files

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to display usage
usage() {
    echo "Usage: ./bump-version.sh <new-version>"
    echo ""
    echo "Example: ./bump-version.sh 0.2.0"
    echo ""
    echo "This will update the version in:"
    echo "  - package.json"
    echo "  - src-tauri/tauri.conf.json"
    echo "  - src-tauri/Cargo.toml"
    echo ""
    echo "Version format: MAJOR.MINOR.PATCH (e.g., 1.2.3)"
    exit 1
}

# Function to get current version from package.json
get_current_version() {
    grep -o '"version": "[^"]*"' package.json | cut -d'"' -f4
}

# Function to validate version format
validate_version() {
    if ! [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        echo -e "${RED}Error: Invalid version format. Use MAJOR.MINOR.PATCH (e.g., 0.2.0)${NC}"
        exit 1
    fi
}

# Function to update version in a file
update_version_in_file() {
    local file=$1
    local old_version=$2
    local new_version=$3
    local pattern=$4
    
    if [ ! -f "$file" ]; then
        echo -e "${RED}Error: File $file not found${NC}"
        exit 1
    fi
    
    # Create backup
    cp "$file" "$file.bak"
    
    # Update version based on file type
    case "$file" in
        *.json)
            sed -i '' "s/\"version\": \"$old_version\"/\"version\": \"$new_version\"/" "$file"
            ;;
        *.toml)
            sed -i '' "s/version = \"$old_version\"/version = \"$new_version\"/" "$file"
            ;;
    esac
    
    # Verify the change
    if grep -q "$new_version" "$file"; then
        echo -e "${GREEN}✓ Updated $file${NC}"
        rm "$file.bak"
    else
        echo -e "${RED}✗ Failed to update $file${NC}"
        mv "$file.bak" "$file"
        exit 1
    fi
}

# Main script
echo ""
echo "================================================"
echo "     Simpler Fuel Version Bump Script"
echo "================================================"
echo ""

# Check if version argument is provided
if [ -z "$1" ]; then
    usage
fi

NEW_VERSION=$1

# Validate version format
validate_version "$NEW_VERSION"

# Get current version
CURRENT_VERSION=$(get_current_version)

if [ -z "$CURRENT_VERSION" ]; then
    echo -e "${RED}Error: Could not detect current version${NC}"
    exit 1
fi

echo -e "Current version: ${YELLOW}$CURRENT_VERSION${NC}"
echo -e "New version:     ${GREEN}$NEW_VERSION${NC}"
echo ""

# Confirm with user
read -p "Do you want to proceed with this version bump? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Version bump cancelled."
    exit 0
fi

echo ""
echo "Updating version in all files..."
echo ""

# Update package.json
update_version_in_file "package.json" "$CURRENT_VERSION" "$NEW_VERSION"

# Update tauri.conf.json
update_version_in_file "src-tauri/tauri.conf.json" "$CURRENT_VERSION" "$NEW_VERSION"

# Update Cargo.toml
update_version_in_file "src-tauri/Cargo.toml" "$CURRENT_VERSION" "$NEW_VERSION"

echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}Version successfully bumped to $NEW_VERSION!${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Review the changes: git diff"
echo "  2. Build and test the app"
echo "  3. Commit the changes: git add . && git commit -m 'Bump version to $NEW_VERSION'"
echo "  4. Build for Play Store: npm run tauri android build"
echo ""
echo "Note: The Android versionCode will be auto-generated by Tauri during build."
echo ""
