#!/usr/bin/env node

/**
 * Version Bump Script for Simpler Fuel
 * Updates version across all configuration files
 * 
 * Usage: npm run bump-version 0.2.0
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';

// ANSI color codes
const colors = {
  red: '\x1b[31m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  reset: '\x1b[0m'
};

const files = [
  {
    path: 'package.json',
    type: 'json',
    key: 'version'
  },
  {
    path: 'src-tauri/tauri.conf.json',
    type: 'json',
    key: 'version'
  },
  {
    path: 'src-tauri/Cargo.toml',
    type: 'toml',
    key: 'version'
  }
];

function validateVersion(version) {
  const versionRegex = /^\d+\.\d+\.\d+$/;
  return versionRegex.test(version);
}

function getCurrentVersion() {
  try {
    const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    return packageJson.version;
  } catch (error) {
    console.error(`${colors.red}Error reading package.json:${colors.reset}`, error.message);
    process.exit(1);
  }
}

function updateJsonFile(filePath, newVersion) {
  try {
    const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    content.version = newVersion;
    fs.writeFileSync(filePath, JSON.stringify(content, null, 2) + '\n');
    console.log(`${colors.green}✓ Updated ${filePath}${colors.reset}`);
    return true;
  } catch (error) {
    console.error(`${colors.red}✗ Failed to update ${filePath}:${colors.reset}`, error.message);
    return false;
  }
}

function updateTomlFile(filePath, newVersion) {
  try {
    let content = fs.readFileSync(filePath, 'utf8');
    content = content.replace(/version = "[^"]*"/, `version = "${newVersion}"`);
    fs.writeFileSync(filePath, content);
    console.log(`${colors.green}✓ Updated ${filePath}${colors.reset}`);
    return true;
  } catch (error) {
    console.error(`${colors.red}✗ Failed to update ${filePath}:${colors.reset}`, error.message);
    return false;
  }
}

async function promptUser(question) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === 'y');
    });
  });
}

async function main() {
  console.log('\n================================================');
  console.log('     Simpler Fuel Version Bump Script');
  console.log('================================================\n');

  // Get new version from command line
  const newVersion = process.argv[2];

  if (!newVersion) {
    console.log('Usage: npm run bump-version <new-version>');
    console.log('\nExample: npm run bump-version 0.2.0');
    console.log('\nThis will update the version in:');
    files.forEach(file => console.log(`  - ${file.path}`));
    console.log('\nVersion format: MAJOR.MINOR.PATCH (e.g., 1.2.3)\n');
    process.exit(1);
  }

  // Validate version format
  if (!validateVersion(newVersion)) {
    console.error(`${colors.red}Error: Invalid version format. Use MAJOR.MINOR.PATCH (e.g., 0.2.0)${colors.reset}\n`);
    process.exit(1);
  }

  // Get current version
  const currentVersion = getCurrentVersion();
  
  console.log(`Current version: ${colors.yellow}${currentVersion}${colors.reset}`);
  console.log(`New version:     ${colors.green}${newVersion}${colors.reset}\n`);

  // Confirm with user
  const confirmed = await promptUser('Do you want to proceed with this version bump? (y/n) ');
  
  if (!confirmed) {
    console.log('\nVersion bump cancelled.\n');
    process.exit(0);
  }

  console.log('\nUpdating version in all files...\n');

  // Update all files
  let allSuccess = true;
  for (const file of files) {
    if (!fs.existsSync(file.path)) {
      console.error(`${colors.red}✗ File not found: ${file.path}${colors.reset}`);
      allSuccess = false;
      continue;
    }

    if (file.type === 'json') {
      allSuccess = updateJsonFile(file.path, newVersion) && allSuccess;
    } else if (file.type === 'toml') {
      allSuccess = updateTomlFile(file.path, newVersion) && allSuccess;
    }
  }

  if (allSuccess) {
    console.log(`\n${colors.green}================================================${colors.reset}`);
    console.log(`${colors.green}Version successfully bumped to ${newVersion}!${colors.reset}`);
    console.log(`${colors.green}================================================${colors.reset}\n`);
    console.log('Next steps:');
    console.log('  1. Review the changes: git diff');
    console.log('  2. Build and test the app');
    console.log(`  3. Commit the changes: git add . && git commit -m "Bump version to ${newVersion}"`);
    console.log('  4. Build for Play Store: npm run tauri android build\n');
    console.log('Note: The Android versionCode will be auto-generated by Tauri during build.\n');
  } else {
    console.error(`\n${colors.red}Some files failed to update. Please check the errors above.${colors.reset}\n`);
    process.exit(1);
  }
}

main().catch(error => {
  console.error(`${colors.red}Unexpected error:${colors.reset}`, error);
  process.exit(1);
});
